/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import edu.princeton.cs.algs4.Draw;

public class App {

    // Não iremos tratar as possíveis exceções de execução
    public static void main(String[] args) throws Exception {
        Draw desenho = new Draw();
        // dimensão da área de desenho (canvas)
        int dimensao = 800;
        desenho.setXscale(0, 800);
        desenho.setYscale(0, 800);
        // Toda ação de desenho acontecerá em um buffer secundário e este só será visto
        // depois que for invocado o método show()
        desenho.enableDoubleBuffering();

        // determina a proporção que será usada para desenhar todos os elementos
        double fator = 50;
        double xInicial = 200;
        double yInicial = 200;
        int[] time = { 2, 59, 59 };
        Clock c = new Clock(fator, Draw.BLACK, Draw.WHITE, xInicial, yInicial, 1, time);

        while (true) {
            desenho.clear();
            c.runClock(desenho);
            desenho.show();
            Thread.sleep(1000);
        }
    }
}// fim da classe